name: poopy
channels:
  - defaults
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - conda=4.12.0
  - conda-content-trust=0.1.1
  - conda-package-handling=1.8.1
  - cryptography=37.0.1
  - idna=3.3
  - libcxx=12.0.0
  - libffi=3.4.2
  - ncurses=6.3
  - openssl=1.1.1o
  - pip=21.2.4
  - pycosat=0.6.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - python.app=3
  - readline=8.1.2
  - requests=2.27.1
  - ruamel_yaml=0.15.100
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.3
  - tk=8.6.11
  - tqdm=4.64.0
  - tzdata=2022a
  - urllib3=1.26.9
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.12
  - pip:
    - nest-asyncio==1.5.5
