
# this is actually painful
# dtypes = {
#     "Accents": "category",
#     "Brand": "category",
#     "Character": "category",
#     "Character Family": "category",
#     "Color": "category",
#     "Country/Region of Manufacture": "category",
#     "Department": "category",
#     "Fabric Type": "category",
#     "Features": "category",
#     "Handle Drop": "category",
#     "Handle Style": "category",
#     "Handle/Strap Material ": "category",
#     "Lining Material": "category",
#     "MPN": "category",
#     "Material": "category",
#     "MPN": "category",
#     "Lining Material": "category",
#     "Measurement, dimension": "category",
#     "Model": "category",
#     "Occasion": "category",
#     "Pattern": "category",
#     "Pocket Type": "category",
# }
